allowBuilds:
  '@mistweaverco/kulala-cli': true
minimumReleaseAgeExclude:
  - '@mistweaverco/kulala-cli@0.10.5'
  - '@mistweaverco/kulala-cli@0.12.2'
  - '@mistweaverco/kulala-cli@0.12.3'
  - '@mistweaverco/kulala-cli@0.13.0'
